version: 2

jobs:
  build:
    docker:
      - image: mritd/shadowsocks:latest
    steps:
      - checkout
    deployment:
      staging:
        branch: master
        heroku:
          appname: weiliang666
